### ISSUE TITLE
Fullscreen problem windows 10

### ISSUE THREAD

**Issue by lesleyrs** [riksweeney/edgar#63]
When alt-tabbing (or pressing windows key by accident) out of the game, the game either crashes or it starts flashing the screen when resolution changes, I also have some screen tearing in fullscreen.

It's supposed to just revert resolution change and go to the background.

I tried changing fullscreen to fullscreen_desktop but that just made the game quit on any key press.

Btw I was reading your making of page and you mentioned compiling with 02 changed behaviour: https://www.parallelrealities.co.uk/features/makingOfLOE.php

Do you remember what it was that changed? Just curious.

**Comment by riksweeney** [comment]
The compiling issue was to do with the fish in one area of the game. If they hit an underwater door they'd fly off the screen. Once this issue was reported to me I removed the O2 flag as it was only applied to the production builds.

I don't readily have access to a Windows machine anymore, so I'm not sure what to do about the crashes you're experiencing. If I manage to get access to one though I'll see if I can reproduce the issue.

**Comment by lesleyrs** [comment]
Edit again: It does actually crash on Linux sometimes when alt tabbing from fullscreen as well.
